// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'btn': string;
  'default': string;
}
export const cssExports: CssExports;
export default cssExports;
