// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'flex': string;
  'flex-column': string;
}
export const cssExports: CssExports;
export default cssExports;
